drop table if exists public.order_status cascade;
create table if not exists public.order_status (
	id int8 generated by default as identity primary key,
	name text,
	description text
);
insert into public.order_status(name, description) values 
	('Đã nhận đơn', 'Đã nhận được đơn trong hệ thống nhưng chưa được xử lý'),
	('Đang xử lý', 'Đơn của khách hàng đang được xử lý'),
	('Đặt đơn thành công', 'Đơn của khách hàng đã được đặt thành công'),
	('Đơn bị huỷ', 'Khách hàng huỷ đơn'),
	('Đặt đơn không thành công', 'Không thành công vì lý do khác');
	
drop table if exists public.payment_method cascade;
create table if not exists public.payment_method (
	id int8 generated by default as identity primary key,
	name text,
	description text
);
insert into public.payment_method(name, description) values
	('Tiền mặt', 'Thanh toán bằng tiền mặt tại nhà hàng'),
	('Thẻ ghi nợ hoặc thẻ tín dụng', 'Thanh toán bằng thẻ ghi nợ hoặc thẻ tín dụng');

drop table if exists public.customer cascade;
create table if not exists public.customer (
	id int8 generated by default as identity primary key,
	name text,
	email text,
	phone text
);
insert into public.customer(name) values
	('Khách hàng vãng lai');

drop table if exists public.delivery_service cascade;
create table if not exists public.delivery_service (
	id int8 generated by default as identity primary key,
	name text,
	description text
);
insert into public.delivery_service(name, description) values
	('Xanh SM', 'Vận chuyển bằng Xanh SM'),
	('Grab Food', 'Vận chuyển bằng Grab Food'),
	('Shopee Food', 'Vận chuyển bằng Shopee Food');

drop table if exists public.bill_status cascade;
create table if not exists public.bill_status (
	id int8 generated by default as identity primary key,
	name text,
	description text
);
insert into public.bill_status(name, description) values 
	('Chưa thanh toán', 'Khách hàng chưa thanh toán hoá đơn'),
	('Đã thanh toán', 'Khách đã thanh toán hoá đơn'),
	('Bị huỷ', 'Hoá đơn bị huỷ');
	
drop table if exists public.table_status cascade;
create table if not exists public.table_status (
	id int8 generated by default as identity primary key,
	name text,
	description text
);
insert into public.table_status (name, description) values 
	('Khả dụng', 'Bàn trống, chưa có khách hàng sử dụng hay đặt trước'),
	('Đặt trước', 'Bàn đã được đặt trước'),
	('Đang sử dụng', 'Bàn đang được khách hàng sử dụng'),
	('Hỏng', 'Bàn bị hỏng');

drop table if exists public.item_type cascade;
create table if not exists public.item_type (
	id int8 generated by default as identity primary key,
	name text,
	description text
);
insert into public.item_type (name, description) values
	('Khai vị', 'Món khai vị'),
	('Chính', 'Món ăn chính'),
	('Tráng miệng', 'Món tráng miệng'),
	('Đồ uống', 'Đồ uống các loại');

drop table if exists public.menu_item cascade;
create table if not exists public.menu_item (
	id int8 generated by default as identity primary key,
	type_id int8 not null references public.item_type (id),
	name text,
	description text,
	price float8
);
INSERT INTO public.menu_item (id, type_id, name, description, price) VALUES
-- Khai vị (Type ID = 1)
(1, 1, 'Gỏi Ngó Sen Tôm Thịt', 'Gỏi thanh mát, tôm thịt đậm đà', 115000),
(2, 1, 'Súp Cua Tóc Tiên', 'Súp sệt thơm ngon, bổ dưỡng', 85000),
(3, 1, 'Chả Giò Rế Tôm Mực', 'Giòn rụm, nhân hải sản tươi', 125000),
-- Chính (Type ID = 2)
(4, 2, 'Bò Lúc Lắc Khoai Tây', 'Thăn bò mềm sốt bơ tỏi', 245000),
(5, 2, 'Cá Kho Tộ', 'Cá lóc kho tộ kiểu miền Tây', 165000),
(6, 2, 'Gà Kho Sả Ớt', 'Gà ta kho đậm vị sả nồng', 145000),
(7, 2, 'Sườn Xào Chua Ngọt', 'Sườn non sốt đậm đà', 185000),
(8, 2, 'Tôm Ram Mặn Ngọt', 'Tôm thẻ ram vỏ giòn', 195000),
-- Tráng miệng (Type ID = 3)
(9, 3, 'Chè Khúc Bạch', 'Khúc bạch béo, nước đường thanh', 45000),
(10, 3, 'Rau Câu Dừa Tươi', 'Thạch dừa nguyên chất mát lạnh', 35000),
(11, 3, 'Bánh Flan Caramel', 'Bánh mịn mượt, thơm trứng sữa', 35000),
-- Đồ uống (Type ID = 4)
(12, 4, 'Trà Đào Cam Sả', 'Trà đào thanh mát giải nhiệt', 55000),
(13, 4, 'Sinh Tố Bơ', 'Bơ sáp xay mịn béo ngậy', 65000),
(14, 4, 'Nước Chanh Dây', 'Chua thanh, giàu Vitamin C', 45000),
(15, 4, 'Cà Phê Sữa Đá', 'Cà phê phin truyền thống', 35000),
(16, 4, 'Nước Ép Cam Tươi', 'Cam vắt nguyên chất 100%', 50000);

SELECT setval('menu_item_id_seq', (SELECT max(id) FROM public.menu_item));


drop table if exists public.ingredient cascade;
create table if not exists public.ingredient (
	id int8 generated by default as identity primary key,
	name text,
	description text,
	unit text
);
INSERT INTO public.ingredient (id, name, description, unit) VALUES
-- Nhóm rau củ quả
(1, 'Ngó sen', 'Ngó sen tươi làm sạch', 'gram'),
(2, 'Cà rốt', 'Cà rốt Đà Lạt', 'gram'),
(3, 'Hành tây', 'Hành tây trắng', 'gram'),
(4, 'Ớt chuông', 'Ớt chuông xanh và đỏ', 'gram'),
(5, 'Khoai tây', 'Khoai tây vàng chiên', 'gram'),
(6, 'Cà chua', 'Cà chua chín', 'gram'),
(7, 'Sả', 'Sả cây băm hoặc đập dập', 'gram'),
(8, 'Ớt', 'Ớt hiểm hoặc ớt sừng', 'gram'),
(9, 'Hành tím', 'Hành tím băm', 'gram'),
(10, 'Tỏi', 'Tỏi lý sơn băm', 'gram'),
(11, 'Khoai môn', 'Khoai môn cao thái sợi', 'gram'),
-- Nhóm thịt cá hải sản
(12, 'Tôm tươi', 'Tôm thẻ hoặc tôm đất', 'gram'),
(13, 'Thịt ba chỉ', 'Thịt heo ba chỉ rút sườn', 'gram'),
(14, 'Thịt cua', 'Thịt cua biển đã bóc vỏ', 'gram'),
(15, 'Ức gà', 'Thịt lườn gà non', 'gram'),
(16, 'Thịt thăn bò', 'Thịt bò thăn mềm', 'gram'),
(17, 'Cá lóc', 'Cá lóc đồng làm sạch', 'gram'),
(18, 'Thịt gà', 'Đùi hoặc cánh gà', 'gram'),
(19, 'Sườn non', 'Sườn non heo', 'gram'),
(20, 'Mực', 'Mực lá băm nhỏ', 'gram'),
-- Nhóm lỏng & Gia vị đặc thù
(21, 'Nước mắm', 'Nước mắm cá cơm 40 độ đạm', 'ml'),
(22, 'Nước cốt chanh', 'Nước cốt chanh tươi', 'ml'),
(23, 'Nước dùng gà', 'Nước ninh xương gà nguyên chất', 'ml'),
(24, 'Nước dừa tươi', 'Nước dừa xiêm', 'ml'),
(25, 'Giấm gạo', 'Giấm gạo lên men', 'ml'),
(26, 'Sữa tươi', 'Sữa tươi không đường', 'ml'),
(27, 'Sữa đặc', 'Sữa đặc có đường', 'ml'),
(28, 'Kem tươi', 'Whipping cream', 'ml'),
(29, 'Cốt dừa', 'Nước cốt dừa đậm đặc', 'ml'),
(30, 'Cốt cà phê', 'Cà phê phin nguyên chất', 'ml'),
-- Nhóm khác
(31, 'Trứng gà', 'Trứng gà ta', 'gram'), -- Quy đổi 1 quả ~ 50g
(32, 'Trứng cút', 'Trứng cút sạch', 'gram'), -- Quy đổi 10 quả ~ 100g
(33, 'Tóc tiên', 'Rong tóc tiên khô', 'gram'),
(34, 'Bột năng', 'Bột năng loại 1', 'gram'),
(35, 'Bánh tráng rế', 'Xấp bánh tráng rế', 'gram'),
(36, 'Đường', 'Đường cát trắng/Đường phèn', 'gram'),
(37, 'Gelatin', 'Bột hoặc lá gelatin', 'gram'),
(38, 'Hạnh nhân', 'Hạnh nhân lát rang', 'gram'),
(39, 'Vải thiều', 'Vải tươi hoặc đóng hộp', 'gram'),
(40, 'Bơ sáp', 'Bơ sáp chín', 'gram'),
(41, 'Chanh dây', 'Cốt chanh dây nguyên chất', 'ml'),
(42, 'Cam tươi', 'Nước cam vắt nguyên chất', 'ml');

-- Cập nhật lại sequence của ID
SELECT setval('ingredient_id_seq', (SELECT max(id) FROM public.ingredient));


drop table if exists public.restaurant_table cascade;
create table if not exists public.restaurant_table (
	id int8 generated by default as identity primary key,
	status_id int8 not null references public.table_status(id),
	num_sits int8,
	description text
);

drop table if exists public.bill cascade;
create table if not exists public.bill (
	id int8 generated by default as identity primary key,
	payment_method_id int8 not null references public.payment_method(id),
	delivery_service_id int8 not null references public.delivery_service(id),
	customer_id int8 not null references public.customer(id),
	status_id int8 not null references public.bill_status(id),
	created_at timestamptz,
	total_payment float8
);

drop table if exists public.order cascade;
create table if not exists public.order (
	id int8 generated by default as identity primary key,
	bill_id int8 not null references public.bill(id),
	table_id int8 not null references public.restaurant_table(id),
	status_id int8 not null references public.order_status(id),
	created_at timestamptz
);


drop table if exists public.order_item cascade;
create table if not exists public.order_item (
	order_id int8 references public.order(id),
	item_id int8 references public.menu_item(id),
	amount float8,
	customer_note text,
	primary key (order_id, item_id)
);

drop table if exists public.item_ingredient cascade;
create table if not exists public.item_ingredient (
	item_id int8 references public.menu_item(id),
	ingredient_id int8 references public.ingredient(id),
	amount float8,
	primary key (item_id, ingredient_id)
);
INSERT INTO public.item_ingredient (item_id, ingredient_id, amount) VALUES
-- Gỏi Ngó Sen
(1, 1, 300), (1, 12, 200), (1, 13, 150), (1, 2, 100), (1, 22, 50), (1, 21, 30),
-- Súp Cua
(2, 14, 150), (2, 15, 100), (2, 31, 50), (2, 32, 100), (2, 33, 10), (2, 34, 50), (2, 23, 800),
-- Chả Giò Rế
(3, 12, 150), (3, 20, 150), (3, 11, 100), (3, 31, 20), (3, 35, 50),
-- Bò Lúc Lắc
(4, 16, 400), (4, 5, 200), (4, 3, 100), (4, 4, 150),
-- Cá Kho Tộ
(5, 17, 500), (5, 13, 100), (5, 21, 60), (5, 24, 150),
-- Gà Kho Sả Ớt
(6, 18, 500), (6, 7, 50), (6, 8, 10), (6, 21, 40),
-- Sườn Xào Chua Ngọt
(7, 19, 500), (7, 6, 100), (7, 25, 40), (7, 36, 30),
-- Tôm Ram
(8, 12, 300), (8, 36, 20), (8, 21, 20),
-- Chè Khúc Bạch
(9, 28, 200), (9, 26, 200), (9, 37, 20), (9, 36, 100), (9, 38, 20), (9, 39, 150),
-- Rau Câu Dừa
(10, 24, 1000), (10, 34, 10), (10, 29, 100), (10, 36, 150),
-- Bánh Flan
(11, 31, 250), (11, 26, 400), (11, 27, 100), (11, 36, 50),
-- Trà Đào Cam Sả
(12, 42, 50), (12, 7, 20), (12, 39, 60),
-- Sinh Tố Bơ
(13, 40, 200), (13, 26, 50), (13, 27, 30),
-- Nước Chanh Dây
(14, 41, 50), (14, 36, 40),
-- Cà Phê Sữa Đá
(15, 30, 50), (15, 27, 30),
-- Nước Ép Cam
(16, 42, 250), (16, 36, 10);

drop table if exists public.ingredient_amount cascade;
create table if not exists public.ingredient_amount (
	id int8 generated by default as identity primary key,
	ingredient_id int8 not null references public.ingredient(id),
	amount float8,
	created_at timestamptz
);
INSERT INTO public.ingredient_amount (ingredient_id, amount, created_at)
SELECT id, 10000, now() -- Khởi tạo mỗi loại 10kg hoặc 10 lít
FROM public.ingredient;